server:
  port: 9090

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xiaohu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
      static-path-pattern: /webapp/**
    resources:
      static-locations: classpath:/webapp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bai.xiaohu.pojo

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

#默认显示条数
constants:
  default:
    pageSize: 10

# LOG4J配置
logging:
  level:
    com.bai.xiaohu: debug

